using OblivionVoice.Client.Animation;
int count=0;
void Check(bool value,string message){if(!value)throw new Exception(message);count++;}
var motion=new MouthMotion();
Check(motion.Update(0,.016f)==0,"Silence leaves the mouth closed");
var opening=motion.Update(1,.02f);
Check(opening>0&&opening<.5f,"Opening blends across frames");
var higher=motion.Update(1,.02f);
Check(higher>opening&&higher<1,"Opening converges without overshoot");
var falling=motion.Update(0,.02f);
Check(falling>0&&falling<higher,"Speech ends with a blended close");
for(int i=0;i<50;i++)motion.Update(0,.02f);
Check(motion.Amount==0,"Silence eventually releases the facial override exactly");
var a=new MouthMotion();var b=new MouthMotion();
for(int i=0;i<10;i++)a.Update(.6f,.01f);
for(int i=0;i<5;i++)b.Update(.6f,.02f);
Check(MathF.Abs(a.Amount-b.Amount)<.00001f,"Opening independent of update rate");
for(int i=0;i<10;i++)a.Update(0,.01f);
for(int i=0;i<5;i++)b.Update(0,.02f);
Check(MathF.Abs(a.Amount-b.Amount)<.00001f,"Closing independent of update rate");
var before=a.Amount;a.Update(1,float.NaN);a.Update(1,-1);a.Update(1,0);
Check(a.Amount==before,"Invalid elapsed times cannot corrupt a pose");
for(int i=0;i<10;i++)a.Update(float.NaN,.1f);
Check(a.Amount==0,"Invalid levels settle closed");
Check(Enumerable.Range(0,100).Select(_=>a.Update(100,.05f)).All(v=>v is >=0 and <=1),"Loud input remains bounded");
a.Reset();Check(a.Amount==0,"Disconnect resets a pose");
Check(Enumerable.Range(0,10).All(_=>a.Update(-10,.01f)==0),"Negative levels do not open a mouth");

var applied=new List<(string Actor,float Amount)>();var released=new List<string>();var forgotten=new List<string>();
var controller=new MouthAnimationController<string>((actor,amount)=>applied.Add((actor,amount)),released.Add,forgotten.Add);
MouthActor<string> Talk(string id,float level=1,bool allowed=true)=>new(id,id+"-fresh-pawn",level,allowed);
controller.Update([Talk("local"),Talk("remote")],true,.65f,.033f);
Check(applied.Count==2&&controller.Count==2,"Local and remote voices each get a pose");
Check(applied.All(p=>p.Amount>0&&p.Amount<.65f),"Strength scales a blended pose");
controller.Update([Talk("local",0),Talk("remote",1,false)],true,.65f,.033f);
Check(released.SequenceEqual(new[]{"remote-fresh-pawn"}),"Dialogue immediately releases that player's voice pose");
Check(controller.Count==1,"Dialoguing character no longer has a voice envelope");
for(int i=0;i<40;i++)controller.Update([Talk("local",0)],true,.65f,.033f);
Check(controller.Count==0&&released.Contains("local-fresh-pawn"),"Silence closes and releases a local pose");
controller.Update([Talk("gone")],true,.65f,.033f);
controller.Update([],true,.65f,.033f);
Check(forgotten.Contains("gone")&&!released.Contains("gone-fresh-pawn"),"Disappeared actor is not dereferenced for cleanup");
controller.Update([Talk("local")],true,.65f,.033f);released.Clear();
controller.Update([Talk("local")],false,.65f,.033f);
Check(controller.Count==0&&released.Count==1,"Disabling animation restores active faces immediately");
controller.Update([Talk("local")],true,.65f,.033f);released.Clear();
controller.Update([Talk("local")],true,0,.033f);
Check(controller.Count==0&&released.Count==1,"Zero strength removes overrides");
applied.Clear();controller.Update([Talk("local"),Talk("local")],true,.65f,.033f);
Check(applied.Count==1,"Loopback/duplicate identity cannot animate the local mouth twice");
controller.ForgetAll();Check(controller.Count==0&&forgotten.Contains("local"),"Session reset clears owned state");
controller.Update([Talk("new",float.NaN)],true,.65f,.033f);
Check(controller.Count==0,"Invalid audio cannot acquire a facial override");
Console.WriteLine($"{count} mouth animation checks passed.");
